# Generated by Django 5.1.3 on 2024-12-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_task_deadline_alter_task_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, unique=True),
        ),
    ]
