# Generated by Django 5.1.3 on 2024-12-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_task_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
