# Generated by Django 5.1.3 on 2024-12-16 10:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_task_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('user', 'email')},
        ),
    ]
