# Generated by Django 5.1.3 on 2024-12-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_task_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_user_email',
        ),
    ]
